language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
branches:
  only:
    - master
    - /^greenkeeper.*$/
before_install:
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - npm run verify-ci

after_script: greenkeeper-lockfile-upload

after_success:
  - npm install -g travis-deploy-once@4
  - travis-deploy-once "npm run semantic-release"
  - npx codecov
